### PR TITLE
Set og:image to Restate logo

### PR DESCRIPTION
**Pull request by pcholakov**
This updates the preview for Restate docs links. See: https://docusaurus.io/docs/next/api/themes/configuration#meta-image.

image

### CODE REVIEW

**Review by tillrohrmann — APPROVED** [review]
Thanks for this improvement @pcholakov. LGTM. +1 for merging.

**Comment by pcholakov** [comment]
Jack pointed me to https://socialsharepreview.com/?url=https://da0ea2bb.documentation-beg.pages.dev/ - there are definitely some improvements needed before merging!

At the very least, create a proper aspect ratio logo. TIL!

image

**Comment by pcholakov** [comment]
> The recommended image ratio for an og:image is 1.91:1. The optimal size would be 1200 x 630.

**Comment by pcholakov** [comment]
Fixed by adding a logo with added padding to the proper aspect ratio – the Docusaurus preview renders the tag on the preview branch with an incorrect base URL so https://socialsharepreview.com/ reports it as broken but it should be fine once merged:

```
<meta data-rh="true" property="og:image" content="https://docs.restate.dev/img/restate-og.png">
```

/cc: @jackkleeman

**Review by jackkleeman — APPROVED** [review]

**Pull request merged**
