### PR TITLE
Serialization guide for Typescript

### LINKED ISSUE #379: Document Raw handlers and Accept annotation
See https://github.com/restatedev/sdk-java/blob/main/sdk-api-gen/src/test/java/dev/restate/sdk/CodegenTest.java#L111

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Fix #379

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
The new page: https://4c0ea596.documentation-beg.pages.dev/develop/ts/serialization

**Comment by gvdongen** [comment]
Maybe we should add an example of a Serde implementation as well? Just to show the template?
For Python, I did this as follows: https://python-quickstart.documentation-beg.pages.dev/develop/python/serialization
Or do you think that is too much?

**Review by gvdongen — APPROVED** [review]
Besides that LGTM :+1:

**Comment by slinkydeveloper** [comment]
I think it's ok, it's a simple enough interface, people will figure out themselves.

**Comment by slinkydeveloper** [comment]
What I think would help tough is [serving the tsdocs](https://github.com/restatedev/sdk-typescript/issues/213), so we could link the `Serde` interface from here and one could immediately see how it looks like.

**Pull request merged**
