### PR TITLE
Add port 9072 everywhere (via ranges)

### PR DESCRIPTION
**Pull request by jackkleeman**

### CODE REVIEW

**Review by tillrohrmann — APPROVED** [review]
LGTM. +1 for merging.

**Comment by AhmedSoliman** [comment]
I'm actually working on removing this port altogether. This http endpoint is being merged with 9070.

**Comment by jackkleeman** [comment]
OK, I can update to have the range only be 9070-9071

**Comment by AhmedSoliman** [comment]
@jackkleeman Yes.

**Pull request merged**
